export const SOURCE_IS_LOADING = 'SOURCE_IS_LOADING';
export const SOURCE_HAS_ERRORED = 'SOURCE_HAS_ERRORED';
export const FETCH_SOURCE_DATA_SUCCESS = 'FETCH_SOURCE_DATA_SUCCESS';

export const ARTICLE_IS_LOADING = 'ARTICLE_IS_LOADING';
export const ARTICLE_HAS_ERRORED = 'ARTICLE_HAS_ERRORED';
export const FETCH_ARTICLE_DATA_SUCCESS = 'FETCH_ARTICLE_DATA_SUCCESS';

export const IS_LOGGED_IN = 'IS_LOGGED_IN';