export const SOURCE_IS_LOADING = 'SOURCE_IS_LOADING';
export const SOURCE_HAS_ERRORED = 'SOURCE_HAS_ERRORED';
export const fetchSourceDataSuccess = 'fetchSourceDataSuccess';

export const ARTICLE_IS_LOADING = 'ARTICLE_IS_LOADING';
export const ARTICLE_HAS_ERRORED = 'ARTICLE_HAS_ERRORED';
export const FETCH_ARTICLE_DATA_SUCCESS = 'FETCH_ARTICLE_DATA_SUCCESS';

export const SEARCH_SOURCE_SUCCESS = 'SEARCH_SOURCE_SUCCESS';
export const I_AM_NOT_SEARCHING = 'I_AM_NOT_SEARCHING';